notify_toastr:
    scripts:
        - 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'
        - 'https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js'
    styles:
        - 'https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css'
        - 'https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css'
    options: null
