inertia:
    # |--------------------------------------------------------------------------
    # | Root View
    # |--------------------------------------------------------------------------
    # |
    # | This option configures the root view that will be used by Inertia to render
    # | your application's pages. By default, Inertia will use the "base" view.
    # | learn more here: https://github.com/SkipTheDragon/inertia-bundle/blob/master/docs/configuration.md
    root_view: 'base.html.twig'


    # |--------------------------------------------------------------------------
    # | Server-side Rendering
    # |--------------------------------------------------------------------------
    # |
    # | These options configures if and how Inertia uses Server Side Rendering
    # | to pre-render the initial visits made to your application's pages.
    # |
    # | You can specify a custom SSR bundle path, or omit it to let Inertia
    # | try and automatically detect it for you.
    # |
    # | Do note that enabling these options will NOT automatically make SSR work,
    # | as a separate rendering service needs to be available. To learn more,
    # | please visit https://inertiajs.com/server-side-rendering
    ssr:
        enabled: false
        url: 'http://127.0.0.1:13714/render'
