enhavo_media:
    resource: "@EnhavoMediaBundle/Resources/config/routing/admin.yml"
    prefix: /admin

enhavo_media_theme:
    resource: "@EnhavoMediaBundle/Resources/config/routing/theme.yml"
    prefix: /
