imports:
    - { resource: "@MonsieurBizSyliusMediaManagerPlugin/Resources/config/config.yaml" }

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%sylius_core.public_dir%/media/image"
                    - "%sylius_core.public_dir%/media" # Add media folder
twig:
    form_themes: ['@MonsieurBizSyliusMediaManagerPlugin/Admin/MediaManager/Form/_theme.html.twig']
