services:

    #Writelistener for Doctrine mongodb, nothing to change just inject doctrine mongodb
    'ApiPlatform\Core\Bridge\Doctrine\EventListener\WriteListener':
        arguments: ['@doctrine_mongodb']
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 100 }

    #collection generic data provider
    'sol.apiplatform.mongobridge.collectiondataprovider':
        class: Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\DataProvider\CollectionDataProvider
        arguments: ['@doctrine_mongodb', $collectionExtensions: !tagged api_platform.doctrine_mongodb.odm.query_extension.collection]
        tags: [{ name: 'api_platform.collection_data_provider', priority: 2 }]

    # item generic data provider
    'sol.apiplatform.mongobridge.itemdataprovider':
        class: Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\DataProvider\ItemDataProvider
        arguments: ['@doctrine_mongodb', $itemExtensions: !tagged api_platform.doctrine_mongodb.odm.query_extension.item]
        tags: [{ name: 'api_platform.item_data_provider', priority: 2 }]

    # extension activation
    'Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\OrderExtension':
        arguments: ['%api_platform.collection.order%', '@api_platform.metadata.resource.metadata_factory']
        tags:
            - { name: api_platform.doctrine_mongodb.odm.query_extension.collection, event: kernel.view, method: onKernelView, priority: 100 }

    'Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\PaginationExtension':
        arguments:
            - '@doctrine_mongodb'
            - '@request_stack'
            - '@api_platform.metadata.resource.metadata_factory'
            - '%api_platform.collection.pagination.enabled%'
            - '%api_platform.collection.pagination.client_enabled%'
            - '%api_platform.collection.pagination.client_items_per_page%'
            - '%api_platform.collection.pagination.items_per_page%'
            - '%api_platform.collection.pagination.page_parameter_name%'
            - '%api_platform.collection.pagination.enabled_parameter_name%'
            - '%api_platform.collection.pagination.items_per_page_parameter_name%'
            - '%api_platform.collection.pagination.maximum_items_per_page%'
            - '%api_platform.collection.pagination.partial%'
            - '%api_platform.collection.pagination.client_partial%'
            - '%api_platform.collection.pagination.partial_parameter_name%'
        tags:
            - { name: api_platform.doctrine_mongodb.odm.query_extension.collection, event: kernel.view, method: onKernelView, priority: 8 }

    'Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\EagerLoadingExtension':
        arguments:
            - '@api_platform.metadata.property.name_collection_factory'
            - '@api_platform.metadata.property.metadata_factory'
            - '@api_platform.metadata.resource.metadata_factory'
            - '%api_platform.eager_loading.max_joins%'
            - '%api_platform.eager_loading.force_eager%'
            - null
            - null
            - '%api_platform.eager_loading.fetch_partial%'
            - '@serializer.mapping.class_metadata_factory'
        tags:
            - { name: api_platform.doctrine_mongodb.odm.query_extension.item, event: kernel.view, method: onKernelView, priority: 64 }
            - { name: api_platform.doctrine_mongodb.odm.query_extension.collection, event: kernel.view, method: onKernelView, priority: 64 }

    'Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\FilterExtension':
        arguments: ['@api_platform.metadata.resource.metadata_factory', '@api_platform.filter_locator']
        tags:
            - { name: api_platform.doctrine_mongodb.odm.query_extension.collection, event: kernel.view, method: onKernelView, priority: 100 } # rend une r√©ponse donc moins prioritaire

    'Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\Filter\DateFilter':
        arguments: ['@doctrine_mongodb', null, '@logger']
        tags:
            - { name: 'api_platform.filter', id: 'mongo.datefilter' }

    'Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\Filter\ExistFilter':
        arguments: ['@doctrine_mongodb', null, '@logger']
        tags:
            - { name: 'api_platform.filter', id: 'mongo.existfilter' }

    'Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\Filter\NumericFilter':
        arguments: ['@doctrine_mongodb', null, '@logger']
        tags:
            - { name: 'api_platform.filter', id: 'mongo.numericfilter' }

    'Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\Filter\OrderFilter':
        arguments: ['@doctrine_mongodb', null, '@logger']
        tags:
            - { name: 'api_platform.filter', id: 'mongo.orderfilter' }

    'Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\Filter\RangeFilter':
        arguments: ['@doctrine_mongodb', null, '@logger']
        tags:
            - { name: 'api_platform.filter', id: 'mongo.rangefilter' }
