login_gate:
    storages: ['session']       # Attempts storage engine. Available engines: ['orm', 'session', 'mongodb']
    options:
        max_count_attempts: 3
        timeout: 600          # Ban period (in seconds ... 600 = 10 minutes)
        watch_period: 3600

