security:
    providers:
        ldap_user_provider:
            id: PasaiaUdala\AuthBundle\Security\LdapUserProvider

    firewalls:
        main:
            lazy: true
            provider: ldap_user_provider
            # When using multiple authenticators, define the entry_point
            # so Symfony knows which authenticator starts the authentication
            entry_point: PasaiaUdala\AuthBundle\Security\LdapAuthenticator

            custom_authenticators:
                - PasaiaUdala\AuthBundle\Security\LdapAuthenticator
                - PasaiaUdala\AuthBundle\Security\CertificateAuthenticator
            
            logout:
                path: app_logout
                target: app_auth_selector

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/oauth, roles: PUBLIC_ACCESS }
        - { path: ^/auth-selector, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
