when@dev:
    kocal_oxc:
        # The Oxc apps version to use, that you can find at https://github.com/oxc-project/oxc/tags,
        # it follows the pattern "apps_v<apps_version>"
        apps_version: '1.43.0'
