# Read the documentation: http://xiidea.github.io/EasyAuditBundle/
xiidea_easy_audit:
    entity_class: Xiidea\EasyAuditBundle\Entity\BaseAuditLog
    default_logger: false
    user_property : null # or username
