happycode_tenzero_auth:
    # Optional app name displayed in the auth layout.
    app_name: "TenZero"

    # Optional app description displayed in the auth layout.
    app_description: "Built in authentication for TenZero."

    # The class that will be used to authenticate user.
    user_class: '%user_class%'

    # The field that will be used to identify the user.
    user_field: "email"
