enhavo_search_admin:
    resource: "@EnhavoSearchBundle/Resources/config/routing/admin.yml"
    prefix: /admin

enhavo_theme_search:
    resource: "@EnhavoSearchBundle/Resources/config/routing/theme.yml"
    prefix: /
