framework:
    http_client:
        scoped_clients:
            storyblok.client:
                base_uri: '%env(STORYBLOK_API_BASE_URI)%'

services:
    _defaults:
        autowire: true

    SensioLabs\Storyblok\Api\StoryblokClient:
        arguments:
            - '%env(STORYBLOK_API_BASE_URI)%'
            - '%env(STORYBLOK_API_TOKEN)%'

    SensioLabs\Storyblok\Api\StoryblokClientInterface: '@SensioLabs\Storyblok\Api\StoryblokClient'

    SensioLabs\Storyblok\Api\StoriesApi: null
    SensioLabs\Storyblok\Api\StoriesApiInterface: '@SensioLabs\Storyblok\Api\StoriesApi'

    SensioLabs\Storyblok\Api\LinksApi: null
    SensioLabs\Storyblok\Api\LinksAipInterface: '@SensioLabs\Storyblok\Api\LinksApi'
