_sfs_login:
    resource: '@SfsUserBundle/config/routing/login.yaml'

#_sfs_invitation:
#    resource: '@SfsUserBundle/config/routing/invitation.yaml'
#    prefix: "/invitation"

_sfs_reset_password:
    resource: '@SfsUserBundle/config/routing/reset_password.yaml'
    prefix: "/reset-password"

_sfs_change_password:
    resource: '@SfsUserBundle/config/routing/change_password.yaml'
    prefix: "/user/change-password"

#_sfs_register:
#    resource: '@SfsUserBundle/config/routing/register.yaml'
#    prefix: "/register"

_sfs_preferences:
    resource: '@SfsUserBundle/config/routing/preferences.yaml'
    prefix: "/user/preferences"