orbitale_cms_category:
    resource: "@OrbitaleCmsBundle/Controller/CategoryController.php"
    type:     annotation
    prefix:   /category/

orbitale_cms_page:
    resource: "@OrbitaleCmsBundle/Controller/PageController.php"
    type:     annotation
    prefix:   /page/
