edb_admin:
    admin_icon: "code" # See https://fontawesome.com/v5/search?s=solid
    admin_title: "Admin"
    source_prefix: "media_source"
    cache_prefix: "media_cache"
    media_class: ~
    user_class: ~
