wouterj_eloquent:
    driver:   '%env(DB_CONNECTION)%'
    host:     '%env(DB_HOST)%'
    port:     '%env(DB_PORT)%'
    database: '%env(DB_DATABASE)%'
    username: '%env(DB_USERNAME)%'
    password: '%env(DB_PASSWORD)%'
    # Uncomment the following line to enable the Eloquent ORM
    #eloquent: null
