when@dev:
    kocal_biome_js:
        # Biome.js CLI version to use:
        # - "latest_stable": use the latest stable version
        # - "latest_nightly": use the latest nightly version
        # - or a specific version, e.g. "v1.9.4", find available tags at https://github.com/biomejs/biome/tags
        binary_version: 'v1.9.4'
