mercuryseries_inertia:
    # |--------------------------------------------------------------------------
    # | Server-side Rendering
    # |--------------------------------------------------------------------------
    # |
    # | These options configures if and how Inertia uses Server Side Rendering
    # | to pre-render the initial visits made to your application's pages.
    # |
    # | You can specify a custom SSR bundle path, or omit it to let Inertia
    # | try and automatically detect it for you.
    # |
    # | Do note that enabling these options will NOT automatically make SSR work,
    # | as a separate rendering service needs to be available. To learn more,
    # | please visit https://inertiajs.com/server-side-rendering
    ssr:
        enabled: false
        url: 'http://127.0.0.1:13714/render'
        # bundle: '%kernel.project_dir%/public/build-ssr/ssr.js'

    # |--------------------------------------------------------------------------
    # | CSRF Protection
    # |--------------------------------------------------------------------------
    # | CSRF (Cross-Site Request Forgery) protection is a security measure
    # | to prevent malicious websites from making requests on behalf of users
    # | without their consent.
    # |
    # | Inertia provides CSRF protection by configuring CSRF tokens and cookies.
    # | The CSRF cookie is used to store the CSRF token, and it is sent with each
    # | request made to the application. The CSRF token is verified on the server
    # | side to ensure the authenticity of the request.
    # |
    # | To learn more, please visit https://inertiajs.com/csrf-protection
    csrf_cookie:
        expire: 0
        path: /
        domain: null
        secure: true
        sameSite: lax
