# Requires the Asset component and the Twig bundle
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# To expose your documentation as JSON
#app.swagger:
#    path: /api/doc.json
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.swagger }
