# See full config at https://github.com/backup-manager/symfony
bm_backup_manager:
    database:
        development:
            dsn: '%env(resolve:DATABASE_URL)%'
    storage:
        local:
            type: Local
            root: '%kernel.cache_dir%/db'
