services:
    _defaults:
        autowire: true
        autoconfigure: true
    RestContextFr\RestContextFr:
        public: true
        arguments:
            $request: '@behatch.http_call.request'
            $httpCallResultPool: '@behatch.http_call.result_pool'
    behatch.http_call.request:
        class: Behatch\HttpCall\Request
        arguments:
            - '@behat.mink'
        public: false
    behatch.http_call.result_pool:
        class: Behatch\HttpCall\HttpCallResultPool
        public: false