setono_google_analytics:
    gtag:
        properties:
            -   measurement_id: '%env(GOOGLE_ANALYTICS_MEASUREMENT_ID)%'

    # If you want to use tag manager instead of gtag, just remove the lines above and enable tag_manager below
    # tag_manager: null
