dh_doctrine_audit:
    # Configuration reference available at:
    # https://github.com/DamienHarper/DoctrineAuditBundle#configuration

    entities:
#        MyBundle\Entity\MyAuditedEntity1: ~   # all MyAuditedEntity1 properties are audited
#        MyBundle\Entity\MyAuditedEntity2:
#            ignored_columns:                  # properties ignored by the audit process
#                - createdAt
#                - updatedAt
