sulu_redirect_api:
    resource: "@SuluRedirectBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_redirect:
    resource: "@SuluRedirectBundle/Resources/config/routing.yml"
    prefix: /admin/redirects
