storyblok_webhook:
    resource: '@StoryblokBundle/config/routes/webhook.php'

storyblok_content_type:
    resource: '@StoryblokBundle/config/routes/content_type.php'

storyblok_cdn:
    resource: '@StoryblokBundle/config/routes/cdn.php'
