# Read the documentation: https://github.com/Tiloweb/SymfonyPaginationBundle
tiloweb_pagination:
    # The Twig template used to render the pagination
    # template: '@TilowebPagination/pagination.html.twig'

    # Number of page links to show before and after the current page
    # page_range: 4

    # Default number of items per page
    default_items_per_page: 10
