# see https://github.com/FrDeamon/logger-extra-bundle/blob/master/README.md#config-reference
deamon_logger_extra:
    # the application name
    application: ~
    # the handler to update
    handlers: 'main'
    # configuration for all optionnal fields
    config: ~
