# Read more about GraphQLite available options at: https://graphqlite.thecodingmachine.io/docs/symfony-bundle
graphqlite:
    namespace:
        controllers: App\Controller\
        types:
            - App\
