castor:
    vhost:
        url: "%env(CASTOR_VHOST_URL)%"
        nom: "%env(CASTOR_VHOST_NOM)%"
        server: "%env(CASTOR_VHOST_SERVER)%"
        os: "%env(CASTOR_VHOST_OS)%"
        ssl:
            enabled: "%env(bool:CASTOR_VHOST_SSL_ENABLE)%"
            certificate: "%env(CASTOR_VHOST_SSL_CERTIFICATE)%"
            certificate_key: "%env(CASTOR_VHOST_SSL_CERTIFICATE_KEY)%"
