imports:
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/doctrine.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/fos_ck_editor.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/fos_user.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/mopa_bootstrap.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/oneup_flysystem.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/oneup_uploader.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_admin.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_block.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_doctrine_admin.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_media.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_notification.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_user.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/stof_doctrine_extensions.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/symfony_cmf_routing_extra.yaml" }
# Default security configuration
#    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/security.yaml" }

# Set up the serializer to read config file for App Page and User entities
jms_serializer:
    metadata:
        directories:
            NetworkingSonataMediaBundle:
                namespace_prefix: "Sonata\\MediaBundle"
                path: "@NetworkingInitCmsBundle/Resources/config/serializer"
            app:
                namespace_prefix: "App"
                path: "%kernel.project_dir%/config/serializer"


networking_init_cms:
    #Base classes to be used for the page and user entities
    class:
        page: "App\\Entity\\Page"
        user: "App\\Entity\\User"

    # Bootstrap some template settings to get you started
    templates:
        'app_single_column':
            template: "@NetworkingInitCms/sandbox/page/one_column.html.twig"
            name: "Single Column"
            icon: "bundles/networkinginitcms/img/template_header_one_column.png"
            zones:
                - { name: header, class: 'col-md-12' }
                - { name: main_content, class: 'col-md-12'}
        'app_two_column':
            template: "@NetworkingInitCms/sandbox/page/two_column.html.twig"
            name: "Two Column"
            icon: "bundles/networkinginitcms/img/template_header_two_column.png"
            zones:
                - { name: header , class: 'col-md-12'}
                - { name: left , class: 'col-md-3'}
                - { name: right , class: 'col-md-9'}
    cache:
        activate: true #enable for product, false in dev config

    # For more information regarding configuration of the CMS Bundle, please visit the following documentation
    # https://github.com/networking/init-cms-bundle/blob/master/doc/configuration.md
