doctrine:
    dbal:
        # We want to store DateTime objects with milliseconds
        # The solution is built on https://github.com/doctrine/dbal/issues/2873#issuecomment-701052412
        # but instead of using microseconds we use milliseconds
        platform_service: Datana\Doctrine\PostgreSQL\Platform\Doctrine\DBAL\Platforms\PostgreSQLMillisecondsPlatform
