alengo_webspace_settings:
    type_select:
        - 'blocks'
        - 'category'
        - 'categories'
        - 'collection'
        - 'collections'
        - 'contact'
        - 'contacts'
        - 'date'
        - 'dateTime'
        - 'event'
        - 'media'
        - 'medias'
        - 'account'
        - 'accounts'
        - 'page'
        - 'pages'
        - 'snippet'
        - 'snippets'
        - 'string' # default type
        - 'tags'
        - 'time'
        - 'textArea'
        - 'textEditor'