exercise_html_purifier:
    # full configuration reference: http://htmlpurifier.org/live/configdoc/plain.html
    default:
        # the charset used by the original contents
        Core.Encoding: 'UTF-8'
