# Read the documentation: https://github.com/acseo/TypesenseBundle/blob/master/README.md
acseo_typesense:
    typesense:
        url: '%typesense_url%'
        key: '%typesense_key%'
        # Optional : add prefix to all collection names in Typesense
        #collection_prefix: 'app_'
    # Collection settings
    collections: null
