silverback_api_components:
    website_name: New Website
    refresh_token:
        handler_id: silverback.api_component.refresh_token.storage.doctrine
        options:
            class: App\Entity\RefreshToken
        cookie_name: api_component
        ttl: 604800 # 1 week
        database_user_provider: database
    user:
        class_name: App\Entity\User
        email_verification:
            default_value: false
            verify_on_register: true
            verify_on_change: true
            deny_unverified_login: true
            email:
                redirect_path_query: null
                default_redirect_path: /verify-email/{{ username }}/{{ token }}
        password_reset:
            email:
                redirect_path_query: null
                default_redirect_path: /reset-password/{{ username }}/{{ token }}
        new_email_confirmation:
            email:
                redirect_path_query: null
                default_redirect_path: /confirm-new-email/{{ username }}/{{ new_email }}/{{ token }}
    publishable:
        permission: "is_granted('ROLE_ADMIN')"
    route_security:
#        - { route: "/user-area*", security: "is_granted('ROLE_USER')" }
