endroid_cm_sms:
    product_token: '%env(ENDROID_CMSMS_PRODUCT_TOKEN)%'
    defaults:
        sender: 'Endroid' # Should not contain more than 11 characters
        unicode: 'auto'
        minimum_number_of_message_parts: 1
        maximum_number_of_message_parts: 3
